apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-api
  template:
    metadata:
      labels:
        app: mock-api
    spec:
      containers:
        - name: mock-api
          image: employee-mock-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /employees
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /employees
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mock-api
spec:
  selector:
    app: mock-api
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP